### PR TITLE
Add pre commit hook for prettier

### PR DESCRIPTION
**Pull request by farzin-fs**
Adds support for pre-commit git hook which runs prettier on changed files.

_Also, all files have been formatted using prettier._

### CODE REVIEW

**Review by mmazzarolo — CHANGES_REQUESTED** [review]
Hey @farzin-fs :) ! Thank you for your contribution. 

Unfortunately, I need to put this PR on hold for a bit. 

I *think* we should stay unopinionated on style settings/choices as much as possible (like using pre-commit hooks or not) and provide only info on how to use the monorepo + multi-platform apps. I already made the mistake of putting a custom ESLint config, and I might go back on this decision. 
What do you think? 

Additionally, this PR is formatting JSON files in native dirs (iOS/macOS) which I think would result in showing them as merge conflicts when updating to newer versions of React Native 👍

**Comment by farzin-fs** [comment]
> I _think_ we should stay unopinionated on style settings/choices as much as possible (like using pre-commit hooks or not) and provide only info on how to use the monorepo + multi-platform apps. I already made the mistake of putting a custom ESLint config, and I might go back on this decision.
> What do you think?

Personally, I think it’s a good idea to have them already set up and working inside the monorepo, I mean one of the goals of monorepo is to have share configs for all packages at the root level.
And whoever is going to use this repo can simply change the config files to match their personal preferences, Like just changing something in `tsconfig.json` or other configuration files.

> Additionally, this PR is formatting JSON files in native dirs (iOS/macOS) which I think would result in showing them as merge conflicts when updating to newer versions of React Native 👍

Thank you, I will exclude them 🙇🏻

**Comment by mmazzarolo** [comment]
That's fair 👍  
Let's do this, I'll keep this PR on hold until I complete the blog posts that I'm currently working on (about the repo). 
Then I'll come back to this and see if it fits with the vision and/or if it needs to be updated (I'll probably make some other tweaks to the repo in the meanwhile). 
Sounds good?

**Comment by farzin-fs** [comment]
> That's fair 👍
> Let's do this, I'll keep this PR on hold until I complete the blog posts that I'm currently working on (about the repo).
> Then I'll come back to this and see if it fits with the vision and/or if it needs to be updated (I'll probably make some other tweaks to the repo in the meanwhile).
> Sounds good?

Sure thing buddy 🙇🏻  Great repo by the way 👍🏻

**Pull request closed without merging**
